name: MLOps Pipeline CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          echo "Setting up Docker"


      - name: Build Docker image
        run: |
          docker build -t mlops-lab-image .

      - name: Run Docker container
        run: |
          docker run mlops-lab-image

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
